"""
Capa de acceso a datos unificada.
- local: SQLite en el equipo
- sync: SQLite local + sincronización automática con la nube (recomendado)
- remote: API en la nube directamente (requiere internet siempre)
"""
import config

if config.is_remote():
    from api_client import (  # noqa: F401
        init_db,
        get_exchange_rate,
        update_exchange_rate,
        get_categories,
        add_category,
        update_category,
        delete_category,
        get_products,
        add_product,
        update_product,
        delete_product,
        quick_add_stock,
        get_customers,
        add_customer,
        delete_customer,
        register_sale,
        get_sales_history,
        get_sale_details,
        get_pending_credits,
        register_credit_payment,
        get_debtor_accounts,
        get_debtor_details,
        get_daily_balance,
        clear_sales_history,
        get_dashboard_stats,
        export_inventory_csv,
        import_inventory_csv,
    )
elif config.is_sync():
    from sync_data_access import (  # noqa: F401
        init_db,
        get_exchange_rate,
        update_exchange_rate,
        get_categories,
        add_category,
        update_category,
        delete_category,
        get_products,
        add_product,
        update_product,
        delete_product,
        quick_add_stock,
        get_customers,
        add_customer,
        delete_customer,
        register_sale,
        get_sales_history,
        get_sale_details,
        get_pending_credits,
        register_credit_payment,
        get_debtor_accounts,
        get_debtor_details,
        get_daily_balance,
        clear_sales_history,
        get_dashboard_stats,
        export_inventory_csv,
        import_inventory_csv,
    )
else:
    from database import (  # noqa: F401
        init_db,
        get_exchange_rate,
        update_exchange_rate,
        get_categories,
        add_category,
        update_category,
        delete_category,
        get_products,
        add_product,
        update_product,
        delete_product,
        quick_add_stock,
        get_customers,
        add_customer,
        delete_customer,
        register_sale,
        get_sales_history,
        get_sale_details,
        get_pending_credits,
        register_credit_payment,
        get_debtor_accounts,
        get_debtor_details,
        get_daily_balance,
        clear_sales_history,
        get_dashboard_stats,
        export_inventory_csv,
        import_inventory_csv,
    )
